PCB: false
batchsize: 64
color_jitter: false
data_dir: ../../../dataset
droprate: 0.5
erasing_p: 0.5
fp16: false
gpu_ids: '0'
load: None
lr: 0.05
name: ft_ResNet50
nclasses: 751
saved_version: 1mask
stride: 1
train_all: true
use_dense: false
