PCB: false
batchsize: 32
color_jitter: false
data_dir: ../../../dataset
droprate: 0.5
erasing_p: 0
fp16: false
gpu_ids: '0'
load: model/ft_ResNet50/net_29.pth
lr: 0.05
name: ft_ResNet50
nclasses: 751
stride: 2
train_all: false
use_dense: false
